/motores:
  ros__parameters:
    FR:
      legType: "RIGHT"
      motor0:
        motorN: 0
        axisID: 0
        iOffset: 0.3005001401901244
        direction: -1
        calibration_angle: 35.6
        joint_limit_min: -30.0
        joint_limit_max: 30.0
      motor1:
        motorN: 0
        axisID: 1
        iOffset: 1.564062506556511
        direction: -1
        calibration_angle: -71.9
        joint_limit_min: -60.0
        joint_limit_max: 45.0
      motor2:
        motorN: 1
        axisID: 2
        iOffset: -3.3035588014125823
        direction: -1
        calibration_angle: 150.2
        joint_limit_min: 0.0
        joint_limit_max: 140.0
    FL:
      legType: "LEFT"
      motor0:
        motorN: 1
        axisID: 3
        iOffset: 0.04181249380111707
        direction: -1
        calibration_angle: -35.6
        joint_limit_min: -30.0
        joint_limit_max: 30.0
      motor1:
        motorN: 0
        axisID: 4
        iOffset: 1.2816874837875367
        direction: 1
        calibration_angle: -71.9
        joint_limit_min: -60.0
        joint_limit_max: 45.0
      motor2:
        motorN: 1
        axisID: 5
        iOffset: -3.1895001578330993
        direction: 1
        calibration_angle: 150.2
        joint_limit_min: 0.0
        joint_limit_max: 140.0
    BL:
      legType: "LEFT"
      motor0:
        motorN: 0
        axisID: 6
        iOffset: -1.1245001411437987
        direction: 1
        calibration_angle: -35.6
        joint_limit_min: -30.0
        joint_limit_max: 30.0
      motor1:
        motorN: 0
        axisID: 7
        iOffset: 1.251187801361084
        direction: 1
        calibration_angle: 0.0
        joint_limit_min: -90.0
        joint_limit_max: 20.0
      motor2:
        motorN: 1
        axisID: 8
        iOffset: -4.055312514305115
        direction: 1
        calibration_angle: 125.0
        joint_limit_min: 0.0
        joint_limit_max: 130.0
    BR:
      legType: "RIGHT"
      motor0:
        motorN: 1
        axisID: 9
        iOffset: 1.0911877012252806
        direction: 1
        calibration_angle: 35.6
        joint_limit_min: -30.0
        joint_limit_max: 30.0
      motor1:
        motorN: 0
        axisID: 10
        iOffset: 1.5096913576126099
        direction: -1
        calibration_angle: 0.0
        joint_limit_min: -90.0
        joint_limit_max: 20.0
      motor2:
        motorN: 1
        axisID: 11
        iOffset: -3.651058614253998
        direction: -1
        calibration_angle: 125.0
        joint_limit_min: 0.0
        joint_limit_max: 130.0
